### ISSUE TITLE
The API fails when creating 2 messages in a row

### ISSUE THREAD

**Issue by bjorno43** [SerafimArts/gitter-api#1]
If the API sends 2 messages in a row in the same event, the API crashes with the following notice:

PHP Notice:  Uninitialized string offset: -1 in /var/www/clients/client1/web4/web/gitter/vendor/serafim/gitter-api/src/Support/JsonStream.php on line 101

To reproduce:

Initialize a stream and have the observer watch a channel for a certain event (being mentioned by a user for example). Now send 2 messages to the stream instead of just 1:

$client->messages->create($roomID, 'Message 1');
$client->messages->create($roomID, 'Message 2');

I came across the issue during the development of a Javascript challenges bot (like Codewars). The idea was that the API congratulated a user on a correct solution. Then performed some database operations followed by a new message letting everyone know that a new challenge was loaded.

Edit:

The error comes after both messages have been succesfully send. Thought that might be important to know.

**Comment by SerafimArts** [comment]
I do not know what kind of error this is. now tested and there are absolutely no errors.

If it's not difficult - can you provide a response from the gitter API with the problem content for the issue?

**Comment by SerafimArts** [comment]
![image](https://user-images.githubusercontent.com/2461257/44941498-5a3eaa00-ada7-11e8-9c92-def9d5d36afe.png)

**Comment by bjorno43** [comment]
To be honest, my knowledge about doing this only goes so far, haha. It seems that the error doesn't pop up on just sending 2 messages. It only happens in my specific use case. Perhaps you could explain me how to log the Gitter response?

If that's too difficult, I could also just make a repo on my Gitter with my source. It's not that much of code and might make it easier for you to see what's going on?

**Comment by SerafimArts** [comment]
@bjorno43 In this case, I propose to cite as an example a small section of code in which the problem is reproduced. And then I'll figure it out and fix it.

Like:
```php
$room = 'ROOM_ID';
$client = new Client('TOKEN_ID');

// Your example code here
```

Naturally, the ID of the room and your personal token should not be sent.

**Comment by SerafimArts** [comment]
P.S. In addition, you can use the logging of your requests in order to understand what is happening inside.

`require monolog/logger`

```php
// Monolog
$logger = new Logger('gitter', [new StreamHandler('php://stdout')]);

// Gitter
$client = new Client('API_TOKEN', $logger);
```

It will look something like this: https://travis-ci.org/SerafimArts/gitter-api/jobs/423385461

**Comment by bjorno43** [comment]
I've narrowed the issue down to the database class. Just save [this PDO database class](https://pastebin.com/G5PhJTAe) and require it. Then add this code (edit your db details):

```
/* Database connection details */
define("DB_HOST", "localhost");
define("DB_USER", "");
define("DB_PASS", "");
define("DB_NAME", "");

$db = new Database;
```

inside the observer and send 2 messages to a channel. That'll cause the issue.

Edit: Well obviously put the database details outside of the observer.

**Comment by bjorno43** [comment]
PS: Just in case, this is my entire code that's causing the issue: https://pastebin.com/KT0DnNzF
Make sure to replace username on line 32 to your script's username.

**Comment by SerafimArts** [comment]
@bjorno43 try to upgrade to version 4.0.8 (https://github.com/SerafimArts/gitter-api/releases/tag/4.0.8) The problem should disappear.

**Comment by bjorno43** [comment]
@SerafimArts Confirmed. The issue is resolved. Working perfectly fine now :) Thanks a lot!

**Comment by bjorno43** [comment]
@SerafimArts Perhaps you'll want to do some further testing with this. I've noticed that the API still stops responding on the same issue. Not displaying any error or crash. It simply just stops responding all together. The subscriber function never gets triggered again on any message.

That issue is solved when changing it to just 1 message. So I'm certain it's the same issue.

**Comment by SerafimArts** [comment]
@bjorno43 I encountered this problem too when using the React StreamSelectLoop (default) driver. In this case, it occurs only when there is a subscription to the same channel (stream of messages ie) several times.

Try to replace it with some other: https://github.com/reactphp/event-loop Because in my code there are no errors associated with blocking parallel connections.

Well, or something I do not understand :D

**Comment by bjorno43** [comment]
@SerafimArts Well I've just decided to stick to 1 message on each event. It works and to be fair, it's not really needed to send multiple messages like that.

Again, thanks a lot for all the help and for creating this awesome Gitter API Client implementation! I really wanted to get this working in PHP instead of Node and it's been very easy to use so far. Well done :)
